export {
  DataStoreMigrations,
  DataStoreMigrationsWithVeramo,
  DataStoreEventLoggerMigrations,
  DataStoreContactMigrations,
  DataStoreIssuanceBrandingMigrations,
  DataStoreStatusListMigrations,
  DataStoreDigitalCredentialMigrations,
  DataStoreCredentialDesignMigrations,
  DataStoreMachineStateMigrations,
  DataStorePresentationDefinitionMigrations,
  DataStoreServiceMigrations,
  VeramoDataStoreMigrations,
  VeramoDataStoreEntities,
} from './generic'
