export { parseDid, multibaseToHex, hexToMultibase, MultibaseFormat } from './utils'
export {
  VerifiablePresentationSP,
  UnsignedPresentationSP,
  VerifiableCredentialSP,
  PresentationSubmission,
  CredentialProofSP,
  CredentialStatusSP,
  W3CVerifiableCredentialSP,
  W3CVerifiablePresentationSP,
  ProofPurpose,
  UnsignedCredentialSP,
  Descriptor,
  IParsedDID,
  SignatureTypes,
  IConnectionParty,
  ConnectionTypeEnum,
  IConnection,
  IBasicConnection,
  ConnectionIdentifierEnum,
  IConnectionIdentifier,
  IBasicConnectionIdentifier,
  IConnectionMetadataItem,
  IBasicConnectionMetadataItem,
  IOpenIdConfig,
  IBasicOpenIdConfig,
  IDidAuthConfig,
  IBasicDidAuthConfig,
  ConnectionConfig,
  BasicConnectionConfig
} from './types'
export { SuppliedSigner } from './signers'
