/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Optional advanced AWS SDK client settings.
 * @export
 * @interface AwsClientConfiguration
 */
export interface AwsClientConfiguration {
  /**
   * Amount of time (in milliseconds) to wait when initially establishing a connection before giving up.
   * @type {number}
   * @memberof AwsClientConfiguration
   */
  connectionTimeoutInMillis?: number
  /**
   * Amount of time (in milliseconds) to wait for data to be transferred over an established, open connection before timing out.
   * @type {number}
   * @memberof AwsClientConfiguration
   */
  socketTimeoutInMillis?: number
}

/**
 * Check if a given object implements the AwsClientConfiguration interface.
 */
export function instanceOfAwsClientConfiguration(value: object): value is AwsClientConfiguration {
  return true
}

export function AwsClientConfigurationFromJSON(json: any): AwsClientConfiguration {
  return AwsClientConfigurationFromJSONTyped(json, false)
}

export function AwsClientConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwsClientConfiguration {
  if (json == null) {
    return json
  }
  return {
    connectionTimeoutInMillis: json['connectionTimeoutInMillis'] == null ? undefined : json['connectionTimeoutInMillis'],
    socketTimeoutInMillis: json['socketTimeoutInMillis'] == null ? undefined : json['socketTimeoutInMillis'],
  }
}

export function AwsClientConfigurationToJSON(json: any): AwsClientConfiguration {
  return AwsClientConfigurationToJSONTyped(json, false)
}

export function AwsClientConfigurationToJSONTyped(value?: AwsClientConfiguration | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    connectionTimeoutInMillis: value['connectionTimeoutInMillis'],
    socketTimeoutInMillis: value['socketTimeoutInMillis'],
  }
}
