/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AzureClientSecretCredentialOpts } from './AzureClientSecretCredentialOpts';
import {
    AzureClientSecretCredentialOptsFromJSON,
    AzureClientSecretCredentialOptsToJSON,
} from './AzureClientSecretCredentialOpts';

/**
 * Azure credential options for authenticating to Key Vault. Currently assumes Service Principal with Client Secret.
 * @export
 * @interface AzureCredentialOpts
 */
export interface AzureCredentialOpts {
    /**
     *
     * @type {AzureClientSecretCredentialOpts}
     * @memberof AzureCredentialOpts
     */
    clientSecretCredentialOpts?: AzureClientSecretCredentialOpts;
}

/**
 * Check if a given object implements the AzureCredentialOpts interface.
 */
export function instanceOfAzureCredentialOpts(value: object): value is AzureCredentialOpts {
    return true;
}

export function AzureCredentialOptsFromJSON(json: any): AzureCredentialOpts {
    return AzureCredentialOptsFromJSONTyped(json, false);
}

export function AzureCredentialOptsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureCredentialOpts {
    if (json == null) {
        return json;
    }
    return {

        'clientSecretCredentialOpts': json['clientSecretCredentialOpts'] == null ? undefined : AzureClientSecretCredentialOptsFromJSON(json['clientSecretCredentialOpts']),
    };
}

export function AzureCredentialOptsToJSON(json: any): AzureCredentialOpts {
    return AzureCredentialOptsToJSONTyped(json, false);
}

export function AzureCredentialOptsToJSONTyped(value?: AzureCredentialOpts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'clientSecretCredentialOpts': AzureClientSecretCredentialOptsToJSON(value['clientSecretCredentialOpts']),
    };
}

