/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CoseKey } from './CoseKey'
import { CoseKeyFromJSON, CoseKeyToJSON } from './CoseKey'

/**
 * Represents a cryptographic key pair for COSE (CBOR Object Signing and Encryption) operations.
 * @export
 * @interface CoseKeyPair
 */
export interface CoseKeyPair {
  /**
   *
   * @type {CoseKey}
   * @memberof CoseKeyPair
   */
  privateCoseKey?: CoseKey
  /**
   *
   * @type {CoseKey}
   * @memberof CoseKeyPair
   */
  publicCoseKey: CoseKey
}

/**
 * Check if a given object implements the CoseKeyPair interface.
 */
export function instanceOfCoseKeyPair(value: object): value is CoseKeyPair {
  if (!('publicCoseKey' in value) || value['publicCoseKey'] === undefined) return false
  return true
}

export function CoseKeyPairFromJSON(json: any): CoseKeyPair {
  return CoseKeyPairFromJSONTyped(json, false)
}

export function CoseKeyPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoseKeyPair {
  if (json == null) {
    return json
  }
  return {
    privateCoseKey: json['privateCoseKey'] == null ? undefined : CoseKeyFromJSON(json['privateCoseKey']),
    publicCoseKey: CoseKeyFromJSON(json['publicCoseKey']),
  }
}

export function CoseKeyPairToJSON(json: any): CoseKeyPair {
  return CoseKeyPairToJSONTyped(json, false)
}

export function CoseKeyPairToJSONTyped(value?: CoseKeyPair | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    privateCoseKey: CoseKeyToJSON(value['privateCoseKey']),
    publicCoseKey: CoseKeyToJSON(value['publicCoseKey']),
  }
}
