/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CoseKeyType } from './CoseKeyType'
import { CoseKeyTypeFromJSON, CoseKeyTypeToJSON } from './CoseKeyType'

/**
 * Represents a COSE (CBOR Object Signing and Encryption) key in JSON format.
 * @export
 * @interface CoseKey
 */
export interface CoseKey {
  /**
   *
   * @type {CoseKeyType}
   * @memberof CoseKey
   */
  kty: CoseKeyType
  /**
   * Key identifier (base64url-encoded byte string).
   * @type {string}
   * @memberof CoseKey
   */
  kid?: string
  /**
   * The COSE algorithm identifier (e.g., -7=ES256, -35=ES384, -36=ES512, -8=EdDSA).
   * @type {number}
   * @memberof CoseKey
   */
  alg?: number
  /**
   * The allowed COSE key operations (1=sign, 2=verify, 3=encrypt, 4=decrypt, etc.).
   * @type {Array<number>}
   * @memberof CoseKey
   */
  keyOps?: Array<number>
  /**
   * Base initialization vector (base64url-encoded).
   * @type {string}
   * @memberof CoseKey
   */
  baseIV?: string
  /**
   * The COSE curve identifier (1=P-256, 2=P-384, 3=P-521, 8=secp256k1, 6=Ed25519, etc.).
   * @type {number}
   * @memberof CoseKey
   */
  crv?: number
  /**
   * The x coordinate (base64url-encoded byte string).
   * @type {string}
   * @memberof CoseKey
   */
  x?: string
  /**
   * The y coordinate (base64url-encoded byte string).
   * @type {string}
   * @memberof CoseKey
   */
  y?: string
  /**
   * The private key parameter (base64url-encoded byte string).
   * @type {string}
   * @memberof CoseKey
   */
  d?: string
  /**
   * X.509 certificate chain as base64-encoded certificates.
   * @type {Array<string>}
   * @memberof CoseKey
   */
  x5chain?: Array<string>
}

/**
 * Check if a given object implements the CoseKey interface.
 */
export function instanceOfCoseKey(value: object): value is CoseKey {
  if (!('kty' in value) || value['kty'] === undefined) return false
  return true
}

export function CoseKeyFromJSON(json: any): CoseKey {
  return CoseKeyFromJSONTyped(json, false)
}

export function CoseKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoseKey {
  if (json == null) {
    return json
  }
  return {
    kty: CoseKeyTypeFromJSON(json['kty']),
    kid: json['kid'] == null ? undefined : json['kid'],
    alg: json['alg'] == null ? undefined : json['alg'],
    keyOps: json['key_ops'] == null ? undefined : json['key_ops'],
    baseIV: json['baseIV'] == null ? undefined : json['baseIV'],
    crv: json['crv'] == null ? undefined : json['crv'],
    x: json['x'] == null ? undefined : json['x'],
    y: json['y'] == null ? undefined : json['y'],
    d: json['d'] == null ? undefined : json['d'],
    x5chain: json['x5chain'] == null ? undefined : json['x5chain'],
  }
}

export function CoseKeyToJSON(json: any): CoseKey {
  return CoseKeyToJSONTyped(json, false)
}

export function CoseKeyToJSONTyped(value?: CoseKey | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    kty: CoseKeyTypeToJSON(value['kty']),
    kid: value['kid'],
    alg: value['alg'],
    key_ops: value['keyOps'],
    baseIV: value['baseIV'],
    crv: value['crv'],
    x: value['x'],
    y: value['y'],
    d: value['d'],
    x5chain: value['x5chain'],
  }
}
