/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyInfo } from './KeyInfo';
import {
    KeyInfoFromJSON,
    KeyInfoToJSON,
} from './KeyInfo';

/**
 * Request body for creating a raw signature.
 * @export
 * @interface CreateRawSignature
 */
export interface CreateRawSignature {
    /**
     *
     * @type {KeyInfo}
     * @memberof CreateRawSignature
     */
    keyInfo: KeyInfo;
    /**
     *
     * @type {string}
     * @memberof CreateRawSignature
     */
    input: string;
}

/**
 * Check if a given object implements the CreateRawSignature interface.
 */
export function instanceOfCreateRawSignature(value: object): value is CreateRawSignature {
    if (!('keyInfo' in value) || value['keyInfo'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function CreateRawSignatureFromJSON(json: any): CreateRawSignature {
    return CreateRawSignatureFromJSONTyped(json, false);
}

export function CreateRawSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRawSignature {
    if (json == null) {
        return json;
    }
    return {

        'keyInfo': KeyInfoFromJSON(json['keyInfo']),
        'input': json['input'],
    };
}

export function CreateRawSignatureToJSON(json: any): CreateRawSignature {
    return CreateRawSignatureToJSONTyped(json, false);
}

export function CreateRawSignatureToJSONTyped(value?: CreateRawSignature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'keyInfo': KeyInfoToJSON(value['keyInfo']),
        'input': value['input'],
    };
}

