/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body containing the created signature.
 * @export
 * @interface CreateSignatureResponse
 */
export interface CreateSignatureResponse {
    /**
     * The created signature encoded as a base64 string.
     * @type {string}
     * @memberof CreateSignatureResponse
     */
    signature: string;
}

/**
 * Check if a given object implements the CreateSignatureResponse interface.
 */
export function instanceOfCreateSignatureResponse(value: object): value is CreateSignatureResponse {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function CreateSignatureResponseFromJSON(json: any): CreateSignatureResponse {
    return CreateSignatureResponseFromJSONTyped(json, false);
}

export function CreateSignatureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSignatureResponse {
    if (json == null) {
        return json;
    }
    return {

        'signature': json['signature'],
    };
}

export function CreateSignatureResponseToJSON(json: any): CreateSignatureResponse {
    return CreateSignatureResponseToJSONTyped(json, false);
}

export function CreateSignatureResponseToJSONTyped(value?: CreateSignatureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'signature': value['signature'],
    };
}

