/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body containing the created signature.
 * @export
 * @interface CreateRawSignatureResponse
 */
export interface CreateRawSignatureResponse {
    /**
     * The created signature encoded as a base64 string.
     * @type {string}
     * @memberof CreateRawSignatureResponse
     */
    signature: string;
}

/**
 * Check if a given object implements the CreateRawSignatureResponse interface.
 */
export function instanceOfCreateRawSignatureResponse(value: object): value is CreateRawSignatureResponse {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function CreateRawSignatureResponseFromJSON(json: any): CreateRawSignatureResponse {
    return CreateRawSignatureResponseFromJSONTyped(json, false);
}

export function CreateRawSignatureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRawSignatureResponse {
    if (json == null) {
        return json;
    }
    return {

        'signature': json['signature'],
    };
}

export function CreateRawSignatureResponseToJSON(json: any): CreateRawSignatureResponse {
    return CreateRawSignatureResponseToJSONTyped(json, false);
}

export function CreateRawSignatureResponseToJSONTyped(value?: CreateRawSignatureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'signature': value['signature'],
    };
}

