/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Cryptographic algorithm type.
 * @export
 */
export const CryptoAlg = {
  Ed25519: 'ED25519',
  Ecdsa: 'ECDSA',
  Hmac: 'HMAC',
  Rsa: 'RSA',
} as const
export type CryptoAlg = (typeof CryptoAlg)[keyof typeof CryptoAlg]

export function instanceOfCryptoAlg(value: any): boolean {
  for (const key in CryptoAlg) {
    if (Object.prototype.hasOwnProperty.call(CryptoAlg, key)) {
      if (CryptoAlg[key as keyof typeof CryptoAlg] === value) {
        return true
      }
    }
  }
  return false
}

export function CryptoAlgFromJSON(json: any): CryptoAlg {
  return CryptoAlgFromJSONTyped(json, false)
}

export function CryptoAlgFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoAlg {
  return json as CryptoAlg
}

export function CryptoAlgToJSON(value?: CryptoAlg | null): any {
  return value as any
}

export function CryptoAlgToJSONTyped(value: any, ignoreDiscriminator: boolean): CryptoAlg {
  return value as CryptoAlg
}
