/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ManagedKeyPair } from './ManagedKeyPair';
import {
    ManagedKeyPairFromJSON,
    ManagedKeyPairToJSON,
} from './ManagedKeyPair';

/**
 * Response body containing a generated key pair.
 * @export
 * @interface GenerateKeyResponse
 */
export interface GenerateKeyResponse {
    /**
     *
     * @type {ManagedKeyPair}
     * @memberof GenerateKeyResponse
     */
    keyPair: ManagedKeyPair;
}

/**
 * Check if a given object implements the GenerateKeyResponse interface.
 */
export function instanceOfGenerateKeyResponse(value: object): value is GenerateKeyResponse {
    if (!('keyPair' in value) || value['keyPair'] === undefined) return false;
    return true;
}

export function GenerateKeyResponseFromJSON(json: any): GenerateKeyResponse {
    return GenerateKeyResponseFromJSONTyped(json, false);
}

export function GenerateKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateKeyResponse {
    if (json == null) {
        return json;
    }
    return {

        'keyPair': ManagedKeyPairFromJSON(json['keyPair']),
    };
}

export function GenerateKeyResponseToJSON(json: any): GenerateKeyResponse {
    return GenerateKeyResponseToJSONTyped(json, false);
}

export function GenerateKeyResponseToJSONTyped(value?: GenerateKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'keyPair': ManagedKeyPairToJSON(value['keyPair']),
    };
}

