/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ManagedKeyInfo } from './ManagedKeyInfo'
import { ManagedKeyInfoFromJSON, ManagedKeyInfoToJSON } from './ManagedKeyInfo'

/**
 * Response body containing a managed key.
 * @export
 * @interface GetKeyResponse
 */
export interface GetKeyResponse {
  /**
   *
   * @type {ManagedKeyInfo}
   * @memberof GetKeyResponse
   */
  keyInfo: ManagedKeyInfo
}

/**
 * Check if a given object implements the GetKeyResponse interface.
 */
export function instanceOfGetKeyResponse(value: object): value is GetKeyResponse {
  if (!('keyInfo' in value) || value['keyInfo'] === undefined) return false
  return true
}

export function GetKeyResponseFromJSON(json: any): GetKeyResponse {
  return GetKeyResponseFromJSONTyped(json, false)
}

export function GetKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKeyResponse {
  if (json == null) {
    return json
  }
  return {
    keyInfo: ManagedKeyInfoFromJSON(json['keyInfo']),
  }
}

export function GetKeyResponseToJSON(json: any): GetKeyResponse {
  return GetKeyResponseToJSONTyped(json, false)
}

export function GetKeyResponseToJSONTyped(value?: GetKeyResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    keyInfo: ManagedKeyInfoToJSON(value['keyInfo']),
  }
}
