/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Method used to identify cryptographic keys.
 * @export
 */
export const IdentifierMethod = {
  Jwk: 'JWK',
  Kid: 'KID',
  CoseKey: 'COSE_KEY',
  X5C: 'X5C',
  Did: 'DID',
} as const
export type IdentifierMethod = (typeof IdentifierMethod)[keyof typeof IdentifierMethod]

export function instanceOfIdentifierMethod(value: any): boolean {
  for (const key in IdentifierMethod) {
    if (Object.prototype.hasOwnProperty.call(IdentifierMethod, key)) {
      if (IdentifierMethod[key as keyof typeof IdentifierMethod] === value) {
        return true
      }
    }
  }
  return false
}

export function IdentifierMethodFromJSON(json: any): IdentifierMethod {
  return IdentifierMethodFromJSONTyped(json, false)
}

export function IdentifierMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifierMethod {
  return json as IdentifierMethod
}

export function IdentifierMethodToJSON(value?: IdentifierMethod | null): any {
  return value as any
}

export function IdentifierMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): IdentifierMethod {
  return value as IdentifierMethod
}
