/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Jwk } from './Jwk'
import { JwkFromJSON, JwkToJSON } from './Jwk'

/**
 * Data class representing a cryptographic key pair used with JOSE (JSON Object Signing and Encryption).
 * @export
 * @interface JoseKeyPair
 */
export interface JoseKeyPair {
  /**
   *
   * @type {Jwk}
   * @memberof JoseKeyPair
   */
  privateJwk?: Jwk
  /**
   *
   * @type {Jwk}
   * @memberof JoseKeyPair
   */
  publicJwk: Jwk
}

/**
 * Check if a given object implements the JoseKeyPair interface.
 */
export function instanceOfJoseKeyPair(value: object): value is JoseKeyPair {
  if (!('publicJwk' in value) || value['publicJwk'] === undefined) return false
  return true
}

export function JoseKeyPairFromJSON(json: any): JoseKeyPair {
  return JoseKeyPairFromJSONTyped(json, false)
}

export function JoseKeyPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoseKeyPair {
  if (json == null) {
    return json
  }
  return {
    privateJwk: json['privateJwk'] == null ? undefined : JwkFromJSON(json['privateJwk']),
    publicJwk: JwkFromJSON(json['publicJwk']),
  }
}

export function JoseKeyPairToJSON(json: any): JoseKeyPair {
  return JoseKeyPairToJSONTyped(json, false)
}

export function JoseKeyPairToJSONTyped(value?: JoseKeyPair | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    privateJwk: JwkToJSON(value['privateJwk']),
    publicJwk: JwkToJSON(value['publicJwk']),
  }
}
