/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The encoding format of the cryptographic key.
 * @export
 */
export const KeyEncoding = {
    Cose: 'COSE',
    Jose: 'JOSE'
} as const;
export type KeyEncoding = typeof KeyEncoding[keyof typeof KeyEncoding];


export function instanceOfKeyEncoding(value: any): boolean {
    for (const key in KeyEncoding) {
        if (Object.prototype.hasOwnProperty.call(KeyEncoding, key)) {
            if (KeyEncoding[key as keyof typeof KeyEncoding] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KeyEncodingFromJSON(json: any): KeyEncoding {
    return KeyEncodingFromJSONTyped(json, false);
}

export function KeyEncodingFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyEncoding {
    return json as KeyEncoding;
}

export function KeyEncodingToJSON(value?: KeyEncoding | null): any {
    return value as any;
}

export function KeyEncodingToJSONTyped(value: any, ignoreDiscriminator: boolean): KeyEncoding {
    return value as KeyEncoding;
}

