/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyType } from './KeyType';
import {
    KeyTypeFromJSON,
    KeyTypeToJSON,
} from './KeyType';
import type { KeyVisibility } from './KeyVisibility';
import {
    KeyVisibilityFromJSON,
     KeyVisibilityToJSON,
} from './KeyVisibility';
import type { SignatureAlgorithm } from './SignatureAlgorithm';
import {
    SignatureAlgorithmFromJSON,
    SignatureAlgorithmToJSON,
} from './SignatureAlgorithm';
import type { KeyEncoding } from './KeyEncoding';
import {
    KeyEncodingFromJSON,
    KeyEncodingToJSON,
} from './KeyEncoding';
import type { Jwk } from './Jwk';
import {
    JwkFromJSON,
    JwkToJSON,
} from './Jwk';

/**
 * Information about a cryptographic key, providing metadata and configuration details necessary for cryptographic operations.
 * @export
 * @interface KeyInfo
 */
export interface KeyInfo {
    /**
     * Unique identifier for the cryptographic key. Can be null if the key identifier is not provided.
     * @type {string}
     * @memberof KeyInfo
     */
    kid?: string;
    /**
     *
     * @type {Jwk}
     * @memberof KeyInfo
     */
    key?: Jwk;
    /**
     *
     * @type {SignatureAlgorithm}
     * @memberof KeyInfo
     */
    signatureAlgorithm?: SignatureAlgorithm;
    /**
     *
     * @type {KeyVisibility}
     * @memberof KeyInfo
     */
    keyVisibility?: KeyVisibility;
    /**
     * X.509 certificate chain associated with the key.
     * @type {Array<string>}
     * @memberof KeyInfo
     */
    x5c?: Array<string>;
    /**
     * A reference or alias to the key in the Key Management Service (KMS).
     * @type {string}
     * @memberof KeyInfo
     */
    alias?: string;
    /**
     * The Key Management System (KMS) identifier associated with the key.
     * @type {string}
     * @memberof KeyInfo
     */
    providerId?: string;
    /**
     *
     * @type {KeyType}
     * @memberof KeyInfo
     */
    keyType?: KeyType;
    /**
     *
     * @type {KeyEncoding}
     * @memberof KeyInfo
     */
    keyEncoding?: KeyEncoding;
    /**
     * Additional configuration options as key-value pairs.
     * @type {{ [key: string]: string; }}
     * @memberof KeyInfo
     */
    opts?: { [key: string]: string; };
}



/**
 * Check if a given object implements the KeyInfo interface.
 */
export function instanceOfKeyInfo(value: object): value is KeyInfo {
    return true;
}

export function KeyInfoFromJSON(json: any): KeyInfo {
    return KeyInfoFromJSONTyped(json, false);
}

export function KeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyInfo {
    if (json == null) {
        return json;
    }
    return {

        'kid': json['kid'] == null ? undefined : json['kid'],
        'key': json['key'] == null ? undefined : JwkFromJSON(json['key']),
        'signatureAlgorithm': json['signatureAlgorithm'] == null ? undefined : SignatureAlgorithmFromJSON(json['signatureAlgorithm']),
        'keyVisibility': json['keyVisibility'] == null ? undefined : KeyVisibilityFromJSON(json['keyVisibility']),
        'x5c': json['x5c'] == null ? undefined : json['x5c'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'keyType': json['keyType'] == null ? undefined : KeyTypeFromJSON(json['keyType']),
        'keyEncoding': json['keyEncoding'] == null ? undefined : KeyEncodingFromJSON(json['keyEncoding']),
        'opts': json['opts'] == null ? undefined : json['opts'],
    };
}

export function KeyInfoToJSON(json: any): KeyInfo {
    return KeyInfoToJSONTyped(json, false);
}

export function KeyInfoToJSONTyped(value?: KeyInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kid': value['kid'],
        'key': JwkToJSON(value['key']),
        'signatureAlgorithm': SignatureAlgorithmToJSON(value['signatureAlgorithm']),
        'keyVisibility': KeyVisibilityToJSON(value['keyVisibility']),
        'x5c': value['x5c'],
        'alias': value['alias'],
        'providerId': value['providerId'],
        'keyType': KeyTypeToJSON(value['keyType']),
        'keyEncoding': KeyEncodingToJSON(value['keyEncoding']),
        'opts': value['opts'],
    };
}

