/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of Key Provider. Determines the required configuration settings. - AZURE_KEYVAULT: Microsoft Azure Key Vault or Managed HSM. - AWS_KMS: Amazon Web Services Key Management Service.
 * @export
 */
export const KeyProviderType = {
  Software: 'SOFTWARE',
  AzureKeyvault: 'AZURE_KEYVAULT',
  AwsKms: 'AWS_KMS',
} as const
export type KeyProviderType = (typeof KeyProviderType)[keyof typeof KeyProviderType]

export function instanceOfKeyProviderType(value: any): boolean {
  for (const key in KeyProviderType) {
    if (Object.prototype.hasOwnProperty.call(KeyProviderType, key)) {
      if (KeyProviderType[key as keyof typeof KeyProviderType] === value) {
        return true
      }
    }
  }
  return false
}

export function KeyProviderTypeFromJSON(json: any): KeyProviderType {
  return KeyProviderTypeFromJSONTyped(json, false)
}

export function KeyProviderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyProviderType {
  return json as KeyProviderType
}

export function KeyProviderTypeToJSON(value?: KeyProviderType | null): any {
  return value as any
}

export function KeyProviderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): KeyProviderType {
  return value as KeyProviderType
}
