/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyProviderType } from './KeyProviderType'
import { KeyProviderTypeFromJSON, KeyProviderTypeToJSON } from './KeyProviderType'

/**
 * Response body containing the details of a Key Provider instance.
 * @export
 * @interface KeyProviderResponse
 */
export interface KeyProviderResponse {
  /**
   * The unique identifier assigned to the Key Provider instance upon creation.
   * @type {string}
   * @memberof KeyProviderResponse
   */
  providerId: string
  /**
   *
   * @type {KeyProviderType}
   * @memberof KeyProviderResponse
   */
  type: KeyProviderType
}

/**
 * Check if a given object implements the KeyProviderResponse interface.
 */
export function instanceOfKeyProviderResponse(value: object): value is KeyProviderResponse {
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function KeyProviderResponseFromJSON(json: any): KeyProviderResponse {
  return KeyProviderResponseFromJSONTyped(json, false)
}

export function KeyProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyProviderResponse {
  if (json == null) {
    return json
  }
  return {
    providerId: json['providerId'],
    type: KeyProviderTypeFromJSON(json['type']),
  }
}

export function KeyProviderResponseToJSON(json: any): KeyProviderResponse {
  return KeyProviderResponseToJSONTyped(json, false)
}

export function KeyProviderResponseToJSONTyped(value?: KeyProviderResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    providerId: value['providerId'],
    type: KeyProviderTypeToJSON(value['type']),
  }
}
