/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyType } from './KeyType';
import {
    KeyTypeFromJSON,
    KeyTypeToJSON,
} from './KeyType';
import type { IdentifierMethod } from './IdentifierMethod';
import {
    IdentifierMethodFromJSON,
    IdentifierMethodToJSON,
} from './IdentifierMethod';

/**
 * Represents a key resolver instance with detailed configuration.
 * @export
 * @interface KeyResolver
 */
export interface KeyResolver {
    /**
     * Unique identifier for the resolver.
     * @type {string}
     * @memberof KeyResolver
     */
    resolverId: string;
    /**
     * List of identifier methods supported by this resolver.
     * @type {Array<IdentifierMethod>}
     * @memberof KeyResolver
     */
    supportedIdentifierMethods?: Array<IdentifierMethod>;
    /**
     * List of key types supported by this resolver.
     * @type {Array<KeyType>}
     * @memberof KeyResolver
     */
    supportedKeyTypes?: Array<KeyType>;
}

/**
 * Check if a given object implements the KeyResolver interface.
 */
export function instanceOfKeyResolver(value: object): value is KeyResolver {
    if (!('resolverId' in value) || value['resolverId'] === undefined) return false;
    return true;
}

export function KeyResolverFromJSON(json: any): KeyResolver {
    return KeyResolverFromJSONTyped(json, false);
}

export function KeyResolverFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyResolver {
    if (json == null) {
        return json;
    }
    return {

        'resolverId': json['resolverId'],
        'supportedIdentifierMethods': json['supportedIdentifierMethods'] == null ? undefined : ((json['supportedIdentifierMethods'] as Array<any>).map(IdentifierMethodFromJSON)),
        'supportedKeyTypes': json['supportedKeyTypes'] == null ? undefined : ((json['supportedKeyTypes'] as Array<any>).map(KeyTypeFromJSON)),
    };
}

export function KeyResolverToJSON(json: any): KeyResolver {
    return KeyResolverToJSONTyped(json, false);
}

export function KeyResolverToJSONTyped(value?: KeyResolver | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'resolverId': value['resolverId'],
        'supportedIdentifierMethods': value['supportedIdentifierMethods'] == null ? undefined : ((value['supportedIdentifierMethods'] as Array<any>).map(IdentifierMethodToJSON)),
        'supportedKeyTypes': value['supportedKeyTypes'] == null ? undefined : ((value['supportedKeyTypes'] as Array<any>).map(KeyTypeToJSON)),
    };
}

