/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cryptographic key type identifier.
 * @export
 */
export const KeyType = {
    Okp: 'OKP',
    Ec: 'EC',
    Rsa: 'RSA'
} as const;
export type KeyType = typeof KeyType[keyof typeof KeyType];


export function instanceOfKeyType(value: any): boolean {
    for (const key in KeyType) {
        if (Object.prototype.hasOwnProperty.call(KeyType, key)) {
            if (KeyType[key as keyof typeof KeyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KeyTypeFromJSON(json: any): KeyType {
    return KeyTypeFromJSONTyped(json, false);
}

export function KeyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyType {
    return json as KeyType;
}

export function KeyTypeToJSON(value?: KeyType | null): any {
    return value as any;
}

export function KeyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): KeyType {
    return value as KeyType;
}

