/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the visibility status of a cryptographic key.
 * @export
 */
export const KeyVisibility = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type KeyVisibility = typeof KeyVisibility[keyof typeof KeyVisibility];


export function instanceOfKeyVisibility(value: any): boolean {
    for (const key in KeyVisibility) {
        if (Object.prototype.hasOwnProperty.call(KeyVisibility, key)) {
            if (KeyVisibility[key as keyof typeof KeyVisibility] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KeyVisibilityFromJSON(json: any): KeyVisibility {
    return KeyVisibilityFromJSONTyped(json, false);
}

export function KeyVisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyVisibility {
    return json as KeyVisibility;
}

export function KeyVisibilityToJSON(value?: KeyVisibility | null): any {
    return value as any;
}

export function KeyVisibilityToJSONTyped(value: any, ignoreDiscriminator: boolean): KeyVisibility {
    return value as KeyVisibility;
}

