/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ManagedKeyInfo } from './ManagedKeyInfo';
import {
    ManagedKeyInfoFromJSON,
    ManagedKeyInfoToJSON,
} from './ManagedKeyInfo';

/**
 * Response body containing all the managed keys.
 * @export
 * @interface ListKeysResponse
 */
export interface ListKeysResponse {
    /**
     *
     * @type {Array<ManagedKeyInfo>}
     * @memberof ListKeysResponse
     */
    keys: Array<ManagedKeyInfo>;
}

/**
 * Check if a given object implements the ListKeysResponse interface.
 */
export function instanceOfListKeysResponse(value: object): value is ListKeysResponse {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function ListKeysResponseFromJSON(json: any): ListKeysResponse {
    return ListKeysResponseFromJSONTyped(json, false);
}

export function ListKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListKeysResponse {
    if (json == null) {
        return json;
    }
    return {

        'keys': ((json['keys'] as Array<any>).map(ManagedKeyInfoFromJSON)),
    };
}

export function ListKeysResponseToJSON(json: any): ListKeysResponse {
    return ListKeysResponseToJSONTyped(json, false);
}

export function ListKeysResponseToJSONTyped(value?: ListKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'keys': ((value['keys'] as Array<any>).map(ManagedKeyInfoToJSON)),
    };
}

