/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyProvider } from './KeyProvider'
import { KeyProviderFromJSON, KeyProviderToJSON } from './KeyProvider'

/**
 * Response body containing the details of a Key Provider instance.
 * @export
 * @interface ListKeyProvidersResponse
 */
export interface ListKeyProvidersResponse {
  /**
   *
   * @type {Array<KeyProvider>}
   * @memberof ListKeyProvidersResponse
   */
  providers: Array<KeyProvider>
}

/**
 * Check if a given object implements the ListKeyProvidersResponse interface.
 */
export function instanceOfListKeyProvidersResponse(value: object): value is ListKeyProvidersResponse {
  if (!('providers' in value) || value['providers'] === undefined) return false
  return true
}

export function ListKeyProvidersResponseFromJSON(json: any): ListKeyProvidersResponse {
  return ListKeyProvidersResponseFromJSONTyped(json, false)
}

export function ListKeyProvidersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListKeyProvidersResponse {
  if (json == null) {
    return json
  }
  return {
    providers: (json['providers'] as Array<any>).map(KeyProviderFromJSON),
  }
}

export function ListKeyProvidersResponseToJSON(json: any): ListKeyProvidersResponse {
  return ListKeyProvidersResponseToJSONTyped(json, false)
}

export function ListKeyProvidersResponseToJSONTyped(value?: ListKeyProvidersResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    providers: (value['providers'] as Array<any>).map(KeyProviderToJSON),
  }
}
