/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyType } from './KeyType'
import { KeyTypeFromJSON, KeyTypeToJSON } from './KeyType'
import type { KeyVisibility } from './KeyVisibility'
import { KeyVisibilityFromJSON, KeyVisibilityToJSON } from './KeyVisibility'
import type { SignatureAlgorithm } from './SignatureAlgorithm'
import { SignatureAlgorithmFromJSON, SignatureAlgorithmToJSON } from './SignatureAlgorithm'
import type { KeyEncoding } from './KeyEncoding'
import { KeyEncodingFromJSON, KeyEncodingToJSON } from './KeyEncoding'
import type { Jwk } from './Jwk'
import { JwkFromJSON, JwkToJSON } from './Jwk'

/**
 * Represents a managed cryptographic key information that is guaranteed to be present and resolved, part of a KMS providing concrete access to the key.
 * @export
 * @interface ManagedKeyInfo
 */
export interface ManagedKeyInfo {
  /**
   * Unique identifier for the cryptographic key. Can be null if the key identifier is not provided.
   * @type {string}
   * @memberof ManagedKeyInfo
   */
  kid?: string
  /**
   *
   * @type {Jwk}
   * @memberof ManagedKeyInfo
   */
  key: Jwk
  /**
   *
   * @type {SignatureAlgorithm}
   * @memberof ManagedKeyInfo
   */
  signatureAlgorithm?: SignatureAlgorithm
  /**
   *
   * @type {KeyVisibility}
   * @memberof ManagedKeyInfo
   */
  keyVisibility?: KeyVisibility
  /**
   * X.509 certificate chain associated with the key.
   * @type {Array<string>}
   * @memberof ManagedKeyInfo
   */
  x5c?: Array<string>
  /**
   * A reference or alias to the key in the Key Management Service (KMS).
   * @type {string}
   * @memberof ManagedKeyInfo
   */
  alias: string
  /**
   * The Key Management System (KMS) identifier associated with the key.
   * @type {string}
   * @memberof ManagedKeyInfo
   */
  providerId: string
  /**
   *
   * @type {KeyType}
   * @memberof ManagedKeyInfo
   */
  keyType?: KeyType
  /**
   *
   * @type {KeyEncoding}
   * @memberof ManagedKeyInfo
   */
  keyEncoding?: KeyEncoding
  /**
   * Additional configuration options as key-value pairs.
   * @type {{ [key: string]: string; }}
   * @memberof ManagedKeyInfo
   */
  opts?: { [key: string]: string }
}

/**
 * Check if a given object implements the ManagedKeyInfo interface.
 */
export function instanceOfManagedKeyInfo(value: object): value is ManagedKeyInfo {
  if (!('key' in value) || value['key'] === undefined) return false
  if (!('alias' in value) || value['alias'] === undefined) return false
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  return true
}

export function ManagedKeyInfoFromJSON(json: any): ManagedKeyInfo {
  return ManagedKeyInfoFromJSONTyped(json, false)
}

export function ManagedKeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedKeyInfo {
  if (json == null) {
    return json
  }
  return {
    kid: json['kid'] == null ? undefined : json['kid'],
    key: JwkFromJSON(json['key']),
    signatureAlgorithm: json['signatureAlgorithm'] == null ? undefined : SignatureAlgorithmFromJSON(json['signatureAlgorithm']),
    keyVisibility: json['keyVisibility'] == null ? undefined : KeyVisibilityFromJSON(json['keyVisibility']),
    x5c: json['x5c'] == null ? undefined : json['x5c'],
    alias: json['alias'],
    providerId: json['providerId'],
    keyType: json['keyType'] == null ? undefined : KeyTypeFromJSON(json['keyType']),
    keyEncoding: json['keyEncoding'] == null ? undefined : KeyEncodingFromJSON(json['keyEncoding']),
    opts: json['opts'] == null ? undefined : json['opts'],
  }
}

export function ManagedKeyInfoToJSON(json: any): ManagedKeyInfo {
  return ManagedKeyInfoToJSONTyped(json, false)
}

export function ManagedKeyInfoToJSONTyped(value?: ManagedKeyInfo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    kid: value['kid'],
    key: JwkToJSON(value['key']),
    signatureAlgorithm: SignatureAlgorithmToJSON(value['signatureAlgorithm']),
    keyVisibility: KeyVisibilityToJSON(value['keyVisibility']),
    x5c: value['x5c'],
    alias: value['alias'],
    providerId: value['providerId'],
    keyType: KeyTypeToJSON(value['keyType']),
    keyEncoding: KeyEncodingToJSON(value['keyEncoding']),
    opts: value['opts'],
  }
}
