/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { JoseKeyPair } from './JoseKeyPair'
import { JoseKeyPairFromJSON, JoseKeyPairToJSON } from './JoseKeyPair'
import type { CoseKeyPair } from './CoseKeyPair'
import { CoseKeyPairFromJSON, CoseKeyPairToJSON } from './CoseKeyPair'

/**
 * Represents a key pair used by a crypto provider, encapsulating both JOSE and COSE key pairs.
 * @export
 * @interface ManagedKeyPair
 */
export interface ManagedKeyPair {
  /**
   * Key identifier, may be null.
   * @type {string}
   * @memberof ManagedKeyPair
   */
  kid?: string
  /**
   * Key Management System identifier.
   * @type {string}
   * @memberof ManagedKeyPair
   */
  providerId: string
  /**
   * Reference to the key in the KMS.
   * @type {string}
   * @memberof ManagedKeyPair
   */
  alias: string
  /**
   *
   * @type {CoseKeyPair}
   * @memberof ManagedKeyPair
   */
  cose: CoseKeyPair
  /**
   *
   * @type {JoseKeyPair}
   * @memberof ManagedKeyPair
   */
  jose: JoseKeyPair
}

/**
 * Check if a given object implements the ManagedKeyPair interface.
 */
export function instanceOfManagedKeyPair(value: object): value is ManagedKeyPair {
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  if (!('alias' in value) || value['alias'] === undefined) return false
  if (!('cose' in value) || value['cose'] === undefined) return false
  if (!('jose' in value) || value['jose'] === undefined) return false
  return true
}

export function ManagedKeyPairFromJSON(json: any): ManagedKeyPair {
  return ManagedKeyPairFromJSONTyped(json, false)
}

export function ManagedKeyPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedKeyPair {
  if (json == null) {
    return json
  }
  return {
    kid: json['kid'] == null ? undefined : json['kid'],
    providerId: json['providerId'],
    alias: json['alias'],
    cose: CoseKeyPairFromJSON(json['cose']),
    jose: JoseKeyPairFromJSON(json['jose']),
  }
}

export function ManagedKeyPairToJSON(json: any): ManagedKeyPair {
  return ManagedKeyPairToJSONTyped(json, false)
}

export function ManagedKeyPairToJSONTyped(value?: ManagedKeyPair | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    kid: value['kid'],
    providerId: value['providerId'],
    alias: value['alias'],
    cose: CoseKeyPairToJSON(value['cose']),
    jose: JoseKeyPairToJSON(value['jose']),
  }
}
