/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyType } from './KeyType';
import {
    KeyTypeFromJSON,
    KeyTypeToJSON,
} from './KeyType';
import type { KeyVisibility } from './KeyVisibility';
import {
    KeyVisibilityFromJSON,
    KeyVisibilityToJSON,
} from './KeyVisibility';
import type { SignatureAlgorithm } from './SignatureAlgorithm';
import {
    SignatureAlgorithmFromJSON,
    SignatureAlgorithmToJSON,
} from './SignatureAlgorithm';
import type { KeyEncoding } from './KeyEncoding';
import {
    KeyEncodingFromJSON,
    KeyEncodingToJSON,
} from './KeyEncoding';
import type { Jwk } from './Jwk';
import {
    JwkFromJSON,
    JwkToJSON,
} from './Jwk';

/**
 * Represents a resolved cryptographic key information where the key is guaranteed to be present and resolved, providing concrete access to the key.
 * @export
 * @interface ResolvedKeyInfo
 */
export interface ResolvedKeyInfo {
    /**
     * Unique identifier for the cryptographic key. Can be null if the key identifier is not provided.
     * @type {string}
     * @memberof ResolvedKeyInfo
     */
    kid?: string;
    /**
     *
     * @type {Jwk}
     * @memberof ResolvedKeyInfo
     */
    key: Jwk;
    /**
     *
     * @type {SignatureAlgorithm}
     * @memberof ResolvedKeyInfo
     */
    signatureAlgorithm?: SignatureAlgorithm;
    /**
     *
     * @type {KeyVisibility}
     * @memberof ResolvedKeyInfo
     */
    keyVisibility?: KeyVisibility;
    /**
     * X.509 certificate chain associated with the key.
     * @type {Array<string>}
     * @memberof ResolvedKeyInfo
     */
    x5c?: Array<string>;
    /**
     * A reference or alias to the key in the Key Management Service (KMS).
     * @type {string}
     * @memberof ResolvedKeyInfo
     */
    alias?: string;
    /**
     * The Key Management System (KMS) identifier associated with the key.
     * @type {string}
     * @memberof ResolvedKeyInfo
     */
    providerId?: string;
    /**
     *
     * @type {KeyType}
     * @memberof ResolvedKeyInfo
     */
    keyType?: KeyType;
    /**
     *
     * @type {KeyEncoding}
     * @memberof ResolvedKeyInfo
     */
    keyEncoding?: KeyEncoding;
    /**
     * Additional configuration options as key-value pairs.
     * @type {{ [key: string]: string; }}
     * @memberof ResolvedKeyInfo
     */
    opts?: { [key: string]: string; };
}



/**
 * Check if a given object implements the ResolvedKeyInfo interface.
 */
export function instanceOfResolvedKeyInfo(value: object): value is ResolvedKeyInfo {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function ResolvedKeyInfoFromJSON(json: any): ResolvedKeyInfo {
    return ResolvedKeyInfoFromJSONTyped(json, false);
}

export function ResolvedKeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedKeyInfo {
    if (json == null) {
        return json;
    }
    return {

        'kid': json['kid'] == null ? undefined : json['kid'],
        'key': JwkFromJSON(json['key']),
        'signatureAlgorithm': json['signatureAlgorithm'] == null ? undefined : SignatureAlgorithmFromJSON(json['signatureAlgorithm']),
        'keyVisibility': json['keyVisibility'] == null ? undefined : KeyVisibilityFromJSON(json['keyVisibility']),
        'x5c': json['x5c'] == null ? undefined : json['x5c'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'keyType': json['keyType'] == null ? undefined : KeyTypeFromJSON(json['keyType']),
        'keyEncoding': json['keyEncoding'] == null ? undefined : KeyEncodingFromJSON(json['keyEncoding']),
        'opts': json['opts'] == null ? undefined : json['opts'],
    };
}

export function ResolvedKeyInfoToJSON(json: any): ResolvedKeyInfo {
    return ResolvedKeyInfoToJSONTyped(json, false);
}

export function ResolvedKeyInfoToJSONTyped(value?: ResolvedKeyInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kid': value['kid'],
        'key': JwkToJSON(value['key']),
        'signatureAlgorithm': SignatureAlgorithmToJSON(value['signatureAlgorithm']),
        'keyVisibility': KeyVisibilityToJSON(value['keyVisibility']),
        'x5c': value['x5c'],
        'alias': value['alias'],
        'providerId': value['providerId'],
        'keyType': KeyTypeToJSON(value['keyType']),
        'keyEncoding': KeyEncodingToJSON(value['keyEncoding']),
        'opts': value['opts'],
    };
}

