/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body containing the details of a Key Provider instance.
 * @export
 * @interface SignatureVerificationResponse
 */
export interface SignatureVerificationResponse {
    /**
     * Indicates whether the signature is valid or not.
     * @type {boolean}
     * @memberof SignatureVerificationResponse
     */
    isValid: boolean;
}

/**
 * Check if a given object implements the SignatureVerificationResponse interface.
 */
export function instanceOfSignatureVerificationResponse(value: object): value is SignatureVerificationResponse {
    if (!('isValid' in value) || value['isValid'] === undefined) return false;
    return true;
}

export function SignatureVerificationResponseFromJSON(json: any): SignatureVerificationResponse {
    return SignatureVerificationResponseFromJSONTyped(json, false);
}

export function SignatureVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureVerificationResponse {
    if (json == null) {
        return json;
    }
    return {

        'isValid': json['isValid'],
    };
}

export function SignatureVerificationResponseToJSON(json: any): SignatureVerificationResponse {
    return SignatureVerificationResponseToJSONTyped(json, false);
}

export function SignatureVerificationResponseToJSONTyped(value?: SignatureVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'isValid': value['isValid'],
    };
}

