/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ManagedKeyInfo } from './ManagedKeyInfo'
import { ManagedKeyInfoFromJSON, ManagedKeyInfoToJSON } from './ManagedKeyInfo'

/**
 * Response body containing a stored key.
 * @export
 * @interface StoreKeyResponse
 */
export interface StoreKeyResponse {
  /**
   *
   * @type {ManagedKeyInfo}
   * @memberof StoreKeyResponse
   */
  keyInfo: ManagedKeyInfo
}

/**
 * Check if a given object implements the StoreKeyResponse interface.
 */
export function instanceOfStoreKeyResponse(value: object): value is StoreKeyResponse {
  if (!('keyInfo' in value) || value['keyInfo'] === undefined) return false
  return true
}

export function StoreKeyResponseFromJSON(json: any): StoreKeyResponse {
  return StoreKeyResponseFromJSONTyped(json, false)
}

export function StoreKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreKeyResponse {
  if (json == null) {
    return json
  }
  return {
    keyInfo: ManagedKeyInfoFromJSON(json['keyInfo']),
  }
}

export function StoreKeyResponseToJSON(json: any): StoreKeyResponse {
  return StoreKeyResponseToJSONTyped(json, false)
}

export function StoreKeyResponseToJSONTyped(value?: StoreKeyResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    keyInfo: ManagedKeyInfoToJSON(value['keyInfo']),
  }
}
