/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AwsKmsSetting } from './AwsKmsSetting'
import { AwsKmsSettingFromJSON, AwsKmsSettingToJSON } from './AwsKmsSetting'
import type { AzureKeyVaultSetting } from './AzureKeyVaultSetting'
import { AzureKeyVaultSettingFromJSON, AzureKeyVaultSettingToJSON } from './AzureKeyVaultSetting'

/**
 * Request body for updating an existing Key Provider instance.
 * @export
 * @interface UpdateKeyProvider
 */
export interface UpdateKeyProvider {
  /**
   *
   * @type {AzureKeyVaultSetting}
   * @memberof UpdateKeyProvider
   */
  azureKeyvaultSettings?: AzureKeyVaultSetting
  /**
   *
   * @type {AwsKmsSetting}
   * @memberof UpdateKeyProvider
   */
  awsKmsSettings?: AwsKmsSetting
  /**
   * Whether to enable caching for keys retrieved from this provider.
   * @type {boolean}
   * @memberof UpdateKeyProvider
   */
  cacheEnabled?: boolean
  /**
   * Time-to-live for cached keys in seconds (if cacheEnabled is true).
   * @type {number}
   * @memberof UpdateKeyProvider
   */
  cacheTTLInSeconds?: number
}

/**
 * Check if a given object implements the UpdateKeyProvider interface.
 */
export function instanceOfUpdateKeyProvider(value: object): value is UpdateKeyProvider {
  return true
}

export function UpdateKeyProviderFromJSON(json: any): UpdateKeyProvider {
  return UpdateKeyProviderFromJSONTyped(json, false)
}

export function UpdateKeyProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateKeyProvider {
  if (json == null) {
    return json
  }
  return {
    azureKeyvaultSettings: json['azureKeyvaultSettings'] == null ? undefined : AzureKeyVaultSettingFromJSON(json['azureKeyvaultSettings']),
    awsKmsSettings: json['awsKmsSettings'] == null ? undefined : AwsKmsSettingFromJSON(json['awsKmsSettings']),
    cacheEnabled: json['cacheEnabled'] == null ? undefined : json['cacheEnabled'],
    cacheTTLInSeconds: json['cacheTTLInSeconds'] == null ? undefined : json['cacheTTLInSeconds'],
  }
}

export function UpdateKeyProviderToJSON(json: any): UpdateKeyProvider {
  return UpdateKeyProviderToJSONTyped(json, false)
}

export function UpdateKeyProviderToJSONTyped(value?: UpdateKeyProvider | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    azureKeyvaultSettings: AzureKeyVaultSettingToJSON(value['azureKeyvaultSettings']),
    awsKmsSettings: AwsKmsSettingToJSON(value['awsKmsSettings']),
    cacheEnabled: value['cacheEnabled'],
    cacheTTLInSeconds: value['cacheTTLInSeconds'],
  }
}
