/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body containing the details of the signature verification.
 * @export
 * @interface VerifyRawSignatureResponse
 */
export interface VerifyRawSignatureResponse {
  /**
   * Indicates whether the signature is valid or not.
   * @type {boolean}
   * @memberof VerifyRawSignatureResponse
   */
  isValid: boolean
}

/**
 * Check if a given object implements the VerifyRawSignatureResponse interface.
 */
export function instanceOfVerifyRawSignatureResponse(value: object): value is VerifyRawSignatureResponse {
  if (!('isValid' in value) || value['isValid'] === undefined) return false
  return true
}

export function VerifyRawSignatureResponseFromJSON(json: any): VerifyRawSignatureResponse {
  return VerifyRawSignatureResponseFromJSONTyped(json, false)
}

export function VerifyRawSignatureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRawSignatureResponse {
  if (json == null) {
    return json
  }
  return {
    isValid: json['isValid'],
  }
}

export function VerifyRawSignatureResponseToJSON(json: any): VerifyRawSignatureResponse {
  return VerifyRawSignatureResponseToJSONTyped(json, false)
}

export function VerifyRawSignatureResponseToJSONTyped(value?: VerifyRawSignatureResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    isValid: value['isValid'],
  }
}
