/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SignInput } from './SignInput';
import {
    SignInputFromJSON,
    SignInputToJSON,
} from './SignInput';
import type { Signature } from './Signature';
import {
    SignatureFromJSON,
    SignatureToJSON,
} from './Signature';

/**
 * Request body for verifying a digital signature.
 * @export
 * @interface VerifySimpleSignature
 */
export interface VerifySimpleSignature {
    /**
     *
     * @type {SignInput}
     * @memberof VerifySimpleSignature
     */
    signInput: SignInput;
    /**
     *
     * @type {Signature}
     * @memberof VerifySimpleSignature
     */
    signature: Signature;
}

/**
 * Check if a given object implements the VerifySimpleSignature interface.
 */
export function instanceOfVerifySimpleSignature(value: object): value is VerifySimpleSignature {
    if (!('signInput' in value) || value['signInput'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function VerifySimpleSignatureFromJSON(json: any): VerifySimpleSignature {
    return VerifySimpleSignatureFromJSONTyped(json, false);
}

export function VerifySimpleSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifySimpleSignature {
    if (json == null) {
        return json;
    }
    return {

        'signInput': SignInputFromJSON(json['signInput']),
        'signature': SignatureFromJSON(json['signature']),
    };
}

export function VerifySimpleSignatureToJSON(json: any): VerifySimpleSignature {
    return VerifySimpleSignatureToJSONTyped(json, false);
}

export function VerifySimpleSignatureToJSONTyped(value?: VerifySimpleSignature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'signInput': SignInputToJSON(value['signInput']),
        'signature': SignatureToJSON(value['signature']),
    };
}

