/* tslint:disable */
/* eslint-disable */
/**
 * KMS REST Server API
 * A REST API for managing cryptographic keys and performing signing and verification operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@sphereon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyInfo } from './KeyInfo'
import { KeyInfoFromJSON, KeyInfoToJSON } from './KeyInfo'

/**
 * Request body for verifying a raw signature.
 * @export
 * @interface VerifyRawSignature
 */
export interface VerifyRawSignature {
  /**
   *
   * @type {KeyInfo}
   * @memberof VerifyRawSignature
   */
  keyInfo: KeyInfo
  /**
   *
   * @type {string}
   * @memberof VerifyRawSignature
   */
  input: string
  /**
   *
   * @type {string}
   * @memberof VerifyRawSignature
   */
  signature: string
}

/**
 * Check if a given object implements the VerifyRawSignature interface.
 */
export function instanceOfVerifyRawSignature(value: object): value is VerifyRawSignature {
  if (!('keyInfo' in value) || value['keyInfo'] === undefined) return false
  if (!('input' in value) || value['input'] === undefined) return false
  if (!('signature' in value) || value['signature'] === undefined) return false
  return true
}

export function VerifyRawSignatureFromJSON(json: any): VerifyRawSignature {
  return VerifyRawSignatureFromJSONTyped(json, false)
}

export function VerifyRawSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRawSignature {
  if (json == null) {
    return json
  }
  return {
    keyInfo: KeyInfoFromJSON(json['keyInfo']),
    input: json['input'],
    signature: json['signature'],
  }
}

export function VerifyRawSignatureToJSON(json: any): VerifyRawSignature {
  return VerifyRawSignatureToJSONTyped(json, false)
}

export function VerifyRawSignatureToJSONTyped(value?: VerifyRawSignature | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    keyInfo: KeyInfoToJSON(value['keyInfo']),
    input: value['input'],
    signature: value['signature'],
  }
}
