openapi: 3.0.0
info:
  title: Sphereon OID4VCI API
  version: 1.0.0
  description: |
    Sphereon OpenID for Verifiable Credential Issuance API
    This API allows issuers to provide verifiable credentials to wallets following the OID4VCI specification.

components:
  schemas:
    Error:
      description: Standard error response format
      type: object
      properties:
        error:
          type: string
          description: Error code
          example: invalid_request
        error_description:
          type: string
          description: Human readable error description
          example: The credential offer xyz was not found

    CredentialResponse:
      description: Response containing the issued credential
      type: object
      properties:
        credential:
          oneOf:
            - type: string
            - type: object
          description: The issued credential, either as a JWT string or JSON object
          example: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9..."
        format:
          type: string
          enum:
            - jwt_vc_json
            - jwt_vc
            - ldp_vc
            - jwt_vc_json-ld
            - vc+sd-jwt
            - mso_mdoc
          description: Format of the issued credential
          example: jwt_vc_json
        c_nonce:
          type: string
          description: Nonce for subsequent credential requests
          example: "b326c4ab-16f1-4304-83e1-4637f8fe4207"
        c_nonce_expires_in:
          type: number
          description: Expiration time of the c_nonce in seconds
          example: 300

    IssueStatusResponse:
      type: object
      description: Status of a credential issuance request
      required:
        - createdAt
        - lastUpdatedAt
        - status
      properties:
        createdAt:
          type: number
          description: Unix timestamp of when the request was created
          example: 1706533345000
        lastUpdatedAt:
          type: number
          description: Unix timestamp of the last status update
          example: 1706533346000
        status:
          type: string
          description: Current status of the issuance process
          enum:
            - OFFER_CREATED
            - OFFER_URI_RETRIEVED
            - ACCESS_TOKEN_REQUESTED
            - ACCESS_TOKEN_CREATED
            - CREDENTIAL_REQUEST_RECEIVED
            - CREDENTIAL_ISSUED
            - NOTIFICATION_CREDENTIAL_ACCEPTED
            - NOTIFICATION_CREDENTIAL_DELETED
            - NOTIFICATION_CREDENTIAL_FAILURE
            - ERROR
          example: CREDENTIAL_ISSUED
        error:
          type: string
        clientId:
          type: string

    AuthorizationChallengeRequest:
      type: object
      description: Request to initiate authorization challenge
      properties:
        client_id:
          type: string
          description: Client identifier
          example: "https://wallet.example.com"
        issuer_state:
          type: string
          description: Opaque state from issuer
          example: "a81bc81b-dead-4563-8692-3bc3c7f12897"
        auth_session:
          type: string
          description: Session identifier for associating subsequent requests
          example: "d270fee1-9185-4e60-9901-d291e1338d7a"
        scope:
          type: string
        code_challenge:
          type: string
        code_challenge_method:
          type: string
          enum: [ plain, S256 ]
        presentation_during_issuance_session:
          type: string

    AuthorizationChallengeResponse:
      type: object
      required:
        - authorization_code
      properties:
        authorization_code:
          type: string

    AccessTokenRequest:
      type: object
      required:
        - grant_type
      properties:
        client_id:
          type: string
        code:
          type: string
        code_verifier:
          type: string
        grant_type:
          type: string
          enum:
            - authorization_code
            - urn:ietf:params:oauth:grant-type:pre-authorized_code
            - password
        pre-authorized_code:
          type: string
        redirect_uri:
          type: string
        scope:
          type: string
        user_pin:
          type: string
        tx_code:
          type: string

    AccessTokenResponse:
      type: object
      required:
        - access_token
      properties:
        access_token:
          type: string
        scope:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
        c_nonce:
          type: string
        c_nonce_expires_in:
          type: number
        authorization_pending:
          type: boolean
        interval:
          type: number

    NotificationRequest:
      type: object
      required:
        - event
      properties:
        event:
          type: string
        event_description:
          type: string
        notification_id:
          type: string

    CredentialRequestV1_0_13:
      type: object
      required:
        - format
      properties:
        format:
          type: string
          enum:
            - jwt_vc_json
            - jwt_vc
            - ldp_vc
            - jwt_vc_json-ld
            - vc+sd-jwt
            - mso_mdoc
        credential_identifier:
          type: string
        proof:
          $ref: '#/components/schemas/ProofOfPossession'
        credential_response_encryption:
          type: object
          properties:
            jwk:
              type: object
            alg:
              type: string
            enc:
              type: string

    ProofOfPossession:
      type: object
      required:
        - proof_type
        - jwt
      properties:
        proof_type:
          type: string
          enum: [ jwt ]
        jwt:
          type: string

    CredentialOfferPayload:
      type: object
      description: Core credential offer data
      required:
        - credential_issuer
        - credential_configuration_ids
      properties:
        credential_issuer:
          type: string
          description: URL of the credential issuer
          example: "https://issuer.example.com"
        credential_configuration_ids:
          type: array
          description: Identifiers for the offered credential configurations
          items:
            type: string
          example: [ "university_degree_1", "verified_email_2" ]
        grants:
          type: object
          description: Supported authorization grant types
          example:
            "urn:ietf:params:oauth:grant-type:pre-authorized_code":
              "pre-authorized_code": "d270fee1-9185-4e60-9901-d291e1338d7a"
        client_id:
          type: string

    CredentialOfferRequest:
      type: object
      properties:
        credential_offer:
          $ref: '#/components/schemas/CredentialOfferPayload'
        credential_offer_uri:
          type: string
        baseUri:
          type: string
        scheme:
          type: string
        pinLength:
          type: number
        qrCodeOpts:
          type: object
        credentialDataSupplierInput:
          type: object

    IssuerMetadata:
      description: Credential issuer metadata as defined in the OID4VCI specification
      type: object
      required:
        - credential_configurations_supported
        - credential_issuer
        - credential_endpoint
      properties:
        credential_configurations_supported:
          type: object
          description: Map of supported credential configurations
          additionalProperties:
            $ref: '#/components/schemas/CredentialConfigurationSupported'
        credential_issuer:
          type: string
          description: URL identifying the credential issuer
          example: "https://issuer.example.com"
        credential_endpoint:
          type: string
          description: URL of the credential endpoint
          example: "https://issuer.example.com/credentials"
        authorization_servers:
          type: array
          items:
            type: string
        deferred_credential_endpoint:
          type: string
        notification_endpoint:
          type: string
        token_endpoint:
          type: string
        display:
          type: array
          items:
            $ref: '#/components/schemas/MetadataDisplay'
        authorization_challenge_endpoint:
          type: string

    CredentialConfigurationSupported:
      type: object
      required:
        - format
      properties:
        format:
          type: string
        scope:
          type: string
        cryptographic_binding_methods_supported:
          type: array
          items:
            type: string
        credential_signing_alg_values_supported:
          type: array
          items:
            type: string
        proof_types_supported:
          type: object
        display:
          type: array
          items:
            $ref: '#/components/schemas/CredentialDisplay'

    MetadataDisplay:
      type: object
      properties:
        name:
          type: string
        locale:
          type: string
        logo:
          type: object
          properties:
            url:
              type: string
            alt_text:
              type: string
        background_color:
          type: string
        text_color:
          type: string

    CredentialDisplay:
      type: object
      properties:
        name:
          type: string
        locale:
          type: string
        logo:
          type: object
          properties:
            url:
              type: string
            alt_text:
              type: string
        background_color:
          type: string
        text_color:
          type: string

paths:
  /.well-known/openid-credential-issuer:
    get:
      summary: Get credential issuer metadata
      description: Returns the metadata about the credential issuer's capabilities
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssuerMetadata'

  /.well-known/oauth-authorization-server:
    get:
      summary: Get authorization server metadata
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

  /webapp/credential-offer-status:
    post:
      summary: Get credential issuance status
      description: Check the current status of a credential issuance request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: Identifier of the credential offer
                  example: "b326c4ab-16f1-4304-83e1-4637f8fe4207"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueStatusResponse'
        '404':
          description: Credential offer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /authorization-challenge:
    post:
      summary: Authorization challenge endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationChallengeRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationChallengeResponse'

  /token:
    post:
      summary: Access token endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessTokenRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'

  /credentials:
    post:
      summary: Get credential endpoint
      description: Request issuance of a credential
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequestV1_0_13'
      responses:
        '200':
          description: Successful response with issued credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'

  /notification:
    post:
      summary: Notification endpoint
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '204':
          description: Notification processed successfully
        '400':
          description: Invalid notification request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /webapp/credential-offers/{id}:
    get:
      summary: Get credential offer
      description: Retrieve a specific credential offer by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the credential offer
          schema:
            type: string
          example: "b326c4ab-16f1-4304-83e1-4637f8fe4207"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialOfferPayload'

  /webapp/credential-offers:
    post:
      summary: Create credential offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialOfferRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  uri:
                    type: string
                  userPin:
                    type: string
                  txCode:
                    type: object
